### ISSUE TITLE
[B&A] Parallelization Support for Bidding and Auction Services

### ISSUE THREAD

**Issue by stguav** [privacysandbox/protected-auction-services-docs#17]
Will the Bidding and Auction Services support parallelization with the "contextual" ad request, as discussed in https://github.com/WICG/turtledove/issues/385?

**Comment by chatterjee-priyanka** [comment]
Thanks. 

We have proposed unification of Contextual and FLEDGE flow with Bidding and Auction Services. Refer https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_services_api.md#unified-contextual-and-fledge-auction-flow-with-bidding-and-auction-services for more details.

**Comment by chatterjee-priyanka** [comment]
We support the unified flow / unified ad request. 

Seller's ad server may call B&A while the contextual auction is running. You may read more about the flow here- https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_services_api.md#flow

**Comment by chatterjee-priyanka** [comment]
Parallelizing Contextual / RTB and B&A auctions would be a further latency optimization.

We do plan to work with different SSPs to incorporate further parallelization of contextual / RTB auction and Bidding and Auction services, so that B&A can be called earlier. However, this needs to happen without impacting traffic shaping in seller's ad server. 

We will keep you posted. Thanks.

**Comment by kevinkiklee** [comment]
This issue has been migrated to the new [WICG/protected-auction-services-discussion](https://github.com/WICG/protected-auction-services-discussion) repository. 

Please continue the discussion in the migrated issue here: https://github.com/WICG/protected-auction-services-discussion/issues/12
