### ISSUE TITLE
Deployment of Bidding Scripts

### ISSUE THREAD

**Issue by thegreatfatzby** [privacysandbox/protected-auction-services-docs#52]
We were discussing internally and realized we should get more clarification on the biddingScriptUrl deployment. I had assumed a few things:

- The IG on browser will still need to declare it's biddingScriptUrl for compat btw on-device/TEE, and for k-anon purposes.
- If that changes, request makes it to bidding service w/o it ever having seen that biddingScriptUrl before...what happens? Does it pull it down live?

**Comment by chatterjee-priyanka** [comment]
Hey, 

Sorry about the delay.

- B&A doesn't require (and doesn't support / recommend) adtechs providing _biddingScriptUrl_ in interest group; primarily because fetching code in the request path (and from multiple endpoints per interest group) will add to latency and also due to [payload optimization](https://github.com/privacysandbox/fledge-docs/blob/main/bidding-auction-services-payload-optimization.md) lesser the data in interest groups sent to B&A from the client, the better. 

- B&A (specifically TEE based Bidding server and TEE based Auction server) prefetches adtech code, then precompiles and caches that. However, adtech can provide multiple versions of the code.

Currently, B&A supports fetching code from adtech hosted third party endpoints and cloud storage buckets. We do recommend adtechs hosting their code blobs in cloud storage buckets, given relatively large sized blobs can be stored and multiple versions of code blobs can be supported.  

Multiple versions of code can be prefetched (off the request path) in Bidding / Auction server at server startup and periodically. We do plan to support the pubsub based notification mechanism as well, that can also facilitate adtechs do emergency pushes and Bidding / Auction server can fetch the code blobs from cloud storage buckets if a code blob object is available.

If adtechs support multiple versions of code, then DSP would have the option to specify the version of adtech code blob to be used for a Protected Auction request in the RTB response to the seller. Then seller can set versions similarly and pass those versions in the SelectAdRequest.AuctionConfig; refer [_generate_bid_code_version_](https://github.com/privacysandbox/bidding-auction-servers/blob/main/api/bidding_auction_servers.proto#L332) (the type should be string, we will fix), [score_ad_version](https://github.com/privacysandbox/bidding-auction-servers/blob/main/api/bidding_auction_servers.proto#L386) and so on. 

You may refer to https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_services_system_design.md#code-blob-fetch-and-code-version for more details.

https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_services_api.md#timeline-and-roadmap on the timeline of when different features are supported. I will try to keep this section upto-date. Thanks.

**Comment by kevinkiklee** [comment]
This issue has been migrated to the new [WICG/protected-auction-services-discussion](https://github.com/WICG/protected-auction-services-discussion/issues/12) repository. 

Please continue the discussion in the migrated issue here: https://github.com/WICG/protected-auction-services-discussion/issues/17
