### ISSUE TITLE
reportResult and reportWin Functions Have Different Signatures from On Device

### ISSUE THREAD

**Issue by thegreatfatzby** [privacysandbox/protected-auction-services-docs#68]
Thanks for the [Event Level Reporting](https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_event_level_reporting.md#protected-audience-event-level-reporting-with-bidding-and-auction-services) explainer! 

First thing I notice is that [reportResult](https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_event_level_reporting.md#the-reportresult-specification) and reportWin have different signatures than on device. It seems like browserSignals has been removed, and the table indicates that some of the fields have moved to `sellerReportingMetadata` in `reportResult` or buyer equivalent for `reportWin`. 

I guess a couple of questions:
1. Why have different signatures? 
2. To the extent this is the signature, will buyerReportingId and sellerAndBuyerReportingId be in the `sellerReportingMetadata` or `buyerReportingMetadata`.

**Comment by chatterjee-priyanka** [comment]
Hey, 

1. 
**reportResult()**
(i) The _directFromSellerSignals_ for on-device [reportResult](https://github.com/WICG/turtledove/blob/main/FLEDGE.md#51-seller-reporting-on-render) is optional, it is not relevant for B&A.
(ii) The reason we changed the name of the arg _browserSignals_ to _sellerReportingMetadata_ is because this is actually reporting metadata that is not generated by the browser in case of B&A but by the TEE based Auction server based on different parameters. The contents of _browserSignals_ (for on-device) and _sellerReportingMetadata_ are same.

With that, the [reportResult()](https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_event_level_reporting.md#the-reportresult-specification) for B&A is aligned with on-device.  If you develop reportResult() for on-device browser, it should work on B&A.

**reportWin()**
Similarly [reportWin()](https://github.com/WICG/turtledove/blob/main/FLEDGE.md#52-buyer-reporting-on-render-and-ad-events) for on-device and [reportWin()](https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_event_level_reporting.md#the-reportwin-specification) for B&A are aligned.

(i) The _directFromSellerSignals_ argument for on-device is optional and it is not relevant to B&A.
(ii) The reason we changed the name of the arg _browserSignals_ to _sellerReportingMetadata_ is because this is actually reporting metadata that is not generated by the browser in case of B&A but by the TEE based Auction server based on different parameters. The contents of _browserSignals_ (for on-device) and _sellerReportingMetadata_ are same.

I can confirm reportResult() and reportWin() developed for browser would work in B&A. Some adtechs have validated that. 

2. As far as I know, this was introduced recently for on-device. However, this is a work in progress on the B&A side and we plan to add the support by early October and make a minor update to the reporting explainer. We will keep you posted once it is available / open sourced. 

Thanks!

**Comment by chatterjee-priyanka** [comment]
We are looking for some feedback from adtechs on this reporting question: https://github.com/WICG/turtledove/issues/821

**Comment by kevinkiklee** [comment]
This issue has been migrated to the new [WICG/protected-auction-services-discussion](https://github.com/WICG/protected-auction-services-discussion/issues/12) repository. 

Please continue the discussion in the migrated issue here: https://github.com/WICG/protected-auction-services-discussion/issues/24
